server:
  port: 8080
spring:
  datasource:
    username: heyi
    password: aS576112369
    url: jdbc:mysql://rm-bp1948lwvnonka1j30o.mysql.rds.aliyuncs.com/mamono?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com:
      example:
        mapper : debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaohe.mamono.dao.*

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

map:
  height: 10
  length: 10

country:
  name: "菲律宾、越南、老挝、柬埔寨、缅甸、泰国、马来西亚、文莱、新加坡、印度尼西亚、中国、蒙古、朝鲜、韩国、日本、尼泊尔、不丹、孟加拉国、印度、巴基斯坦、斯里兰卡、马尔代夫
  、哈萨克斯坦、吉尔吉斯斯坦、塔吉克斯坦、乌兹别克斯坦、土库曼斯坦、阿富汗、伊拉克、伊朗、叙利亚、约旦、黎巴嫩、以色列、巴勒斯坦、沙特阿拉伯、巴林、卡塔尔、科威特、阿拉伯联合酋长国（阿联酋）
  、阿曼、也门、格鲁吉亚、亚美尼亚、阿塞拜疆、土耳其、塞浦路斯罗马尼亚、保加利亚、塞尔维亚、马其顿、阿尔巴尼亚、希腊、斯洛文尼亚、克罗地亚、波斯尼亚和墨塞哥维那"
  number:
  minSize:
  maxSize: